version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    networks:
      - internal
  
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672"
      - "15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - internal
  
  vault:
    image: hashicorp/vault:latest
    #ports:
    #  - "8200:8200"
    networks:
      - internal
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "${VAULT_DEV_ROOT_TOKEN_ID}"
  
  consul:
    image: hashicorp/consul:latest
    command: "agent -dev"
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    ports:
      - "8500:8500"
    networks:
      - internal
  
  minio:
    image: minio/minio
    ports:
      - '9000:9000'
    #    volumes:
    #      - minio-data:/data
    networks:
      - internal
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
    ports:
      - "9200:9200" # Elasticsearch HTTP
      - "9300:9300" # Elasticsearch TCP transport
    volumes:
      - esdata:/usr/share/elasticsearch/data
  
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  redis:
    image: redis:latest
    networks:
      - internal

  identity-management.api:
    build:
      context: ./IdentityManagementApi
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
      - vault
      - consul
    networks:
      - internal
    environment:
      ConnectionStrings__DefaultConnection: "Server=postgres;Port=5432;Database=AdvertisementsIdentityDB;User Id=postgres;Password=123456"
      Kestrel__Endpoints__Http__Url: "http://0.0.0.0:5004"
      Logging__LogLevel__Default: "Information"
      Logging__LogLevel__Microsoft.AspNetCore: "Warning"
      Vault__Address: "${VAULT_ADDRESS}"
      Vault__Token: "${VAULT_DEV_ROOT_TOKEN_ID}"
      AllowedHosts: "*"
      JWTSecretKey: "${JWT_SECRET_KEY}"
  
  advertisement-management.api:
    build:
      context: ./AdvertisementManagementApi
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
      - vault
      - consul
    networks:
      - internal
    environment:
      ConnectionStrings__DefaultConnection: "Server=postgres;Port=5432;Database=AdvertisementsDB;User Id=postgres;Password=123456"
      Elasticsearch__Url: "http://elasticsearch:9200"
      Logging__LogLevel__Default: "Information"
      Logging__LogLevel__Microsoft.AspNetCore: "Warning"
      AllowedHosts: "*"
      Kestrel__Endpoints__Http__Url: "http://0.0.0.0:5006"
      Vault__Address: "${VAULT_ADDRESS}"
      Vault__Token: "${VAULT_DEV_ROOT_TOKEN_ID}"
      thumbnail-service: "thumbnail-management.api"
  
  email-sender.api:
    build:
      context: ./EmailSenderApi
      dockerfile: ./Dockerfile
    depends_on:
      - vault
      - consul
      - rabbitmq
    environment:
      vault_token: "${VAULT_DEV_ROOT_TOKEN_ID}"
      vault_address: "${VAULT_ADDRESS}"
      app_port: 5007
      rabbitmq_addr: amqp://guest:guest@rabbitmq:5672/
    networks:
      - internal
  
  thumbnail-management.api:
    build:
      context: ./ThumbnailManagementApi
      dockerfile: ./Dockerfile
    depends_on:
      - minio
      - postgres
      - vault
      - consul
    environment:
      object_storage_address: "minio:9000"
      object_storage_access_key: minioadmin
      object_storage_secret_key: minioadmin
      vault_token: "${VAULT_DEV_ROOT_TOKEN_ID}"
      vault_address: "${VAULT_ADDRESS}"
      thumbnail_grpc_api_port_number: 5002
      host_name: thumbnail-management.api
      thumbnail_management_base_db: "user=postgres password=123456 host=postgres port=5432 sslmode=disable"
      thumbnail_management_full_db: "user=postgres password=123456 host=postgres port=5432 dbname=advertisement_thumbnails sslmode=disable"
    networks:
      - internal
  
  category-management.api:
    build:
      context: ./CategoriesApi
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
      - vault
      - consul
    environment:
      categories_full_db_connection: "user=postgres password=123456 host=postgres port=5432 dbname=category_management sslmode=disable"
      categories_base_db_connection: "user=postgres password=123456 host=postgres port=5432 sslmode=disable"
      vault_token: "${VAULT_DEV_ROOT_TOKEN_ID}"
      vault_address: "${VAULT_ADDRESS}"
    networks:
      - internal

  location-management.api:
    build:
      context: ./LocationsApi
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
      - vault
    environment:
      location_management_base_sdn: "user=postgres password=123456 host=postgres port=5432 sslmode=disable"
      location_management_full_sdn: "user=postgres password=123456 host=postgres port=5432 dbname=location_management sslmode=disable"
      location_app_port: 5010
    networks:
      - internal
  
  api-gateway.app.api:
    build:
      context: ./ApiGateway
      dockerfile: ./Dockerfile
    ports:
      - "5009:5009"
    depends_on:
      - vault
      - postgres
      - identity-management.api
      - category-management.api
      - location-management.api
      - advertisement-management.api
    networks:
      - internal
    restart: always
    environment:
      JWTSecretKey: "${JWT_SECRET_KEY}"
      Logging__LogLevel__Default: Information
      Logging__LogLevel__Microsoft.AspNetCore: Warning
      AllowedHosts: "*"
      Kestrel__Endpoints__http__Url: "http://0.0.0.0:5009"
      Vault__Address: "${VAULT_ADDRESS}"
      Vault__Token: "${VAULT_DEV_ROOT_TOKEN_ID}"

networks:
  internal:
    driver: bridge

volumes:
  esdata:
    driver: local
