version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    networks:
      - internal
  
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - internal
  
  vault:
    image: hashicorp/vault:latest
    #ports:
    #  - "8200:8200"
    networks:
      - internal
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: 58ec2667-a9f4-455b-b89b-914fe565b7ea
  
  consul:
    image: hashicorp/consul:latest
    command: "agent -dev"
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    ports:
      - "8500:8500"
    networks:
      - internal
  
  minio:
    image: minio/minio
    ports:
      - '9000:9000'
    #    volumes:
    #      - minio-data:/data
    networks:
      - internal
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data
  
  redis:
    image: redis:latest
    networks:
      - internal
  secrets-seeder-api:
    build:
      context: ./Seeder
      dockerfile: ./Dockerfile
    environment:
      vault_token: 58ec2667-a9f4-455b-b89b-914fe565b7ea
      vault_address: http://vault:8200
    networks:
      - internal
    depends_on:
      - vault
  
  identity-management.api:
    build:
      context: ./IdentityManagement
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
      - vault
      - consul
      - secrets-seeder-api
    networks:
      - internal
    environment:
      - Kestrel__Endpoints__Http__Url=http://0.0.0.0:5004
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - Vault__Address=http://vault:8200
      - Vault__Token=58ec2667-a9f4-455b-b89b-914fe565b7ea
      - AllowedHosts=*
  
  advertisement-management.api:
    build:
      context: ./AdvertisementManagement
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
      - vault
      - consul
      - secrets-seeder-api
    networks:
      - internal
    environment:
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=AdvertisementsDB;User Id=postgres;Password=123456
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - AllowedHosts=*
      - Kestrel__Endpoints__Http__Url=http://0.0.0.0:5006
      - Vault__Address=http://vault:8200
      - Vault__Token=58ec2667-a9f4-455b-b89b-914fe565b7ea
  
  email-sender:
    build:
      context: ./EmailSender
      dockerfile: ./Dockerfile
    depends_on:
      - vault
      - consul
      - rabbitmq
      - secrets-seeder-api
    environment:
      vault_token: 58ec2667-a9f4-455b-b89b-914fe565b7ea
      vault_address: http://vault:8200
      app_port: 5007
    networks:
      - internal
  
  thumbnail-management:
    build:
      context: ./ThumbnailManagement
      dockerfile: ./Dockerfile
    depends_on:
      - minio
      - postgres
      - vault
      - consul
      - secrets-seeder-api
    environment:
      vault_token: 58ec2667-a9f4-455b-b89b-914fe565b7ea
      vault_address: http://vault:8200
      port_number: 5002
      host_name: thumbnail-management
    networks:
      - internal
  
  category-management.api:
    build:
      context: ./CategoryManagement
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
      - vault
      - consul
      - secrets-seeder-api
    environment:
      vault_token: 58ec2667-a9f4-455b-b89b-914fe565b7ea
      vault_address: http://vault:8200
    networks:
      - internal

  location-management.api:
    build:
      context: ./LocationManagement
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
      - vault
    environment:
      location_management_base_sdn: "user=postgres password=123456 host=postgres port=5432 sslmode=disable"
      location_management_full_sdn: "user=postgres password=123456 host=postgres port=5432 dbname=location_management sslmode=disable"
      location_app_port: 5010
    networks:
      - internal
  
  api-gateway.app.api:
    build:
      context: ./ApiGateway
      dockerfile: ./Dockerfile
    ports:
      - "5009:5009"
    depends_on:
      - vault
      - secrets-seeder-api
      - category-management.api
    networks:
      - internal
    restart: always
    environment:
      - JWTSecretKey=TJ7RzYjU3JrWYsLgqC0gG0CJcT+4W5qz5JtKmFzvKBM=
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - AllowedHosts=*
      - Kestrel__Endpoints__http__Url=http://0.0.0.0:5009
      - Vault__Address=http://vault:8200
      - Vault__Token=58ec2667-a9f4-455b-b89b-914fe565b7ea

networks:
  internal:
    driver: bridge