version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  vault:
    image: hashicorp/vault:latest
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: 58ec2667-a9f4-455b-b89b-914fe565b7ea
    ports:
      - "8200:8200"

  consul:
    image: hashicorp/consul:latest
    command: "agent -dev"
    ports:
      - "8500:8500"
  minio:
    image: minio/minio
    ports:
      - '9000:9000'
    #    volumes:
    #      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data
  
  redis:
    image: redis:latest

  seeder:
    build:
      context: ./Seeder
      dockerfile: ./Dockerfile
    depends_on:
      - vault
  
  api-gateway:
    build:
      context: ./ApiGateway
      dockerfile: ./Dockerfile
    depends_on:
      - seeder

  identity-management:
    build:
      context: ./IdentityManagement
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
      - vault
      - consul
      - seeder

  advertisement-management:
    build:
      context: ./AdvertisementManagement
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
      - vault
      - consul
      - seeder
  
  email-sender:
    build:
      context: ./EmailSender
      dockerfile: ./Dockerfile
    depends_on:
      - vault
      - consul
      - rabbitmq
      - seeder
    environment:
      vault_token: 58ec2667-a9f4-455b-b89b-914fe565b7ea
      vault_address: http://127.0.0.1:8200
      app_port: 5007

  thumbnail-management:
    build:
      context: ./ThumbnailManagement
      dockerfile: ./Dockerfile
    depends_on:
      - minio
      - postgres
      - vault
      - consul
      - seeder
    environment:
      vault_token: 58ec2667-a9f4-455b-b89b-914fe565b7ea
      vault_address: http://127.0.0.1:8200
      port_number: 5002
  
  category-management:
    build:
      context: ./CategoryManagement
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
      - vault
      - consul
      - seeder
    environment:
      vault_token: 58ec2667-a9f4-455b-b89b-914fe565b7ea
      vault_address: http://127.0.0.1:8200

################################################
networks:
  default:
    name: bridge
    external: true