<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdvertisingSystem.Identity.Contract\AdvertisingSystem.Identity.Contract.csproj" />
    <ProjectReference Include="..\AdvertisingSystem.Identity.Domain\AdvertisingSystem.Identity.Domain.csproj" />
    <ProjectReference Include="..\AdvertisingSystem.Identity.Infrastructure\AdvertisingSystem.Identity.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="FluentValidation" Version="11.9.0" />
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="Microsoft.AspNet.Identity.Core" Version="2.2.4" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.1" />
    <PackageReference Include="OpenIddict" Version="5.1.0" />
    <PackageReference Include="OpenIddict.Server.AspNetCore" Version="5.1.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.2.0" />
  </ItemGroup>

</Project>
